type Query {
  "Returns all farming configurations"
  getAllFarmingConfigs: [FarmingConfigType]
  "Returns a single farming configuration"
  getFarmingConfig(id: ID!): FarmingConfigType
  "Returns all recruitment configurations"
  getAllRecruitConfigs: [RecruitConfigType]
  "Returns a single recruitment configuration"
  getRecruitConfig(id: ID!): RecruitConfigType
  "Returns all configurations"
  getAllConfigs: AllConfigsType
  "Returns detailed villages data, both resources and units. If googleDocId is provided and valid, the whole statistics is being stored in google document"
  getVillagesData(googleDocId: ID): Dynamic
  "Returns the details regarding the attack, with the exact execution times for every provided target"
  calculateAttackLaunchTimes(attackScheduler: AttackSchedulerInput!): AttackSchedulerType
  "Returns all scheduled attacks"
  getScheduledAttacks(filter: AttackSchedulerFilter!): [AttackSchedulerType]
  "Returns all relocate units configurations"
  getAllRelocateUnitsConfigs: [RelocateUnitsConfigType]
  "Returns a single relocate units configuration"
  getRelocateUnitsConfig(id: ID!): RelocateUnitsConfigType
}

type Mutation {
  "Creates a farming configuration that is used by the scheduler"
  setFarmingConfig(farmingConfig: FarmingConfigInput!): FarmingConfigType
  "Executes a single farming action immediately, without persisting the configuration"
  activateImmediateFarming(farmingConfig: FarmingConfigInput!): Boolean
  "Creates a recruit configuration that is used by the scheduler"
  setRecruitConfig(recruitConfig: RecruitConfigInput!): RecruitConfigType
  "Executes a single recruit action immediately, without persisting the configuration"
  activateImmediateRecruit(recruitConfig: RecruitConfigInput!): Boolean
  "Executes recruit action of spies, up to the [maxRecruitSpies] number"
  activateImmediateSpyRecruit(spyRecruitConfig: SpyRecruitConfigInput!): Boolean
  "Creates an attack configuration that is used by the scheduler"
  setAttackScheduler(attackScheduler: AttackSchedulerInput!): AttackSchedulerType
  "Executes a single relocate action, without persisting the configuration"
  setRelocateUnitsConfig(relocateConfig: RelocateUnitsConfigInput!): RelocateUnitsConfigType
  "Executes a single relocate action, without persisting the configuration"
  activateRelocateUnits(relocateConfig: RelocateUnitsConfigInput!): Boolean
  activateMoveSpecificUnits(moveSpecificConfig: MoveSpecificUnitsConfigInput!): Boolean
  "Executes a single mass donation action, without persisting the configuration"
  activateMassDonation(massDonationConfig: MassDonationConfigInput!): Boolean
  "Deletes a single farming configuration"
  deleteFarmingConfig(id: ID!): Boolean
  "Deletes all farming configurations"
  deleteAllFarmingConfigs: Boolean
  "Deletes a single recruit configuration"
  deleteRecruitConfig(id: ID!): Boolean
  "Deletes all recruit configurations"
  deleteAllRecruitConfigs: Boolean
  "Deletes all configurations"
  deleteAllConfigs: Boolean
  "Deletes all attack schedulers that are suppose to be executed by the same village"
  deleteChainedAttackSchedulers(chainId: ID!): Boolean
  "Deletes all attack schedulers"
  deleteAllAttackSchedulers: Boolean
  "Deletes a single relocate units configuration"
  deleteRelocateUnitsConfig(id: ID!): Boolean
  "Deletes all relocate units configurations"
  deleteAllRelocateUnitsConfigs: Boolean
}
