type Query {
  getAllAttackConfigs: [AttackConfigType]
  getAttackConfig(id: ID!): AttackConfigType
  getAllRecruitConfigs: [RecruitConfigType]
  getRecruitConfig(id: ID!): RecruitConfigType
  getAllConfigs: AllConfigsType
}

type Mutation {
  setAttackConfig(attackConfig: AttackConfigInput!): AttackConfigType
  deleteAttackConfig(id: ID!): Boolean
  activateImmediateAttack(attackConfig: AttackConfigInput!): Boolean
  setRecruitConfig(recruitConfig: RecruitConfigInput!): RecruitConfigType
  deleteRecruitConfig(id: ID!): Boolean
  activateImmediateRecruit(recruitConfig: RecruitConfigInput!): Boolean
  deleteConfig(id: ID!): Boolean
}
