type Query {
  "Returns all resource deposit configurations"
  getAllResourceDepositConfigs: [ResourceDepositConfigType]
  "Returns a single resource deposit configuration"
  getResourceDepositConfig(id: ID!): ResourceDepositConfigType
}

type Mutation {
  "Creates a resource deposit configuration that is used by the scheduler"
  setResourceDepositConfig(resourceDepositConfig: ResourceDepositConfigInput!): ResourceDepositConfigType
  "Executes a single resource deposit action immediately, without persisting the configuration"
  activateImmediateResourceDeposit(resourceDepositConfig: ResourceDepositConfigInput!): Boolean
  "Deletes a resource deposit configuration"
  deleteResourceDepositConfig(id: ID!): Boolean
  "Deletes all resource deposit configurations"
  deleteAllResourceDepositConfigs: Boolean
}
