type Query {
  getAllAttackConfigs: [AttackConfigType]
  getAttackConfig(id: ID!): AttackConfigType
  getAllRecruitConfigs: [RecruitConfigType]
  getRecruitConfig(id: ID!): RecruitConfigType
  getAllConfigs: AllConfigsType
  getUnitsCount: Boolean
}

type Mutation {
  setAttackConfig(attackConfig: AttackConfigInput!): AttackConfigType
  activateImmediateAttack(attackConfig: AttackConfigInput!): Boolean
  setRecruitConfig(recruitConfig: RecruitConfigInput!): RecruitConfigType
  activateImmediateRecruit(recruitConfig: RecruitConfigInput!): Boolean
  deleteAttackConfig(id: ID!): Boolean
  deleteAllAttackConfigs: Boolean
  deleteRecruitConfig(id: ID!): Boolean
  deleteAllRecruitConfigs: Boolean
  deleteConfig(id: ID!): Boolean
  deleteAllConfigs: Boolean
  activateHealthCheck(intervalInMinutes: Float): Boolean
  deactivateHealthCheck: Boolean
}
