type Query {
  "Returns all trading resources configurations"
  getAllTradingResourcesConfigs: [TradingResourcesConfigType]
  "Returns a single trading resources configuration"
  getTradingResourcesConfig(id: ID!): TradingResourcesConfigType
}

type Mutation {
  "Creates a trading resources configuration that is used by the scheduler"
  setTradingResourcesConfig(tradingResourcesConfig: TradingResourcesConfigInput!): TradingResourcesConfigType
  "Executes a single trading resources action immediately, without persisting the configuration"
  activateImmediateTradingResources(tradingResourcesConfig: TradingResourcesConfigInput!): Boolean
  "Creates a trading resources configuration that is used by the scheduler"
  deleteTradingResourcesConfig(recruitConfig: RecruitConfigInput!): Boolean
  "Executes a single recruit action immediately, without persisting the configuration"
  deleteAllTradingResourcesConfigs(recruitConfig: RecruitConfigInput!): Boolean
}
