type BuildingUpgradeConfigType {
  id: ID
  accountId: String
  villageName: String
  buildingCommands: [BuildingCommandType]
  maxLevelPerBuildingName: MaxLevelPerBuildingNameType
  buildingPriority: BuildingPriorityType
  executedTimes: Int
  failedTimes: Int
  executedAt: DateTime
  nextExecutionAt: DateTime
}

type MaxLevelPerBuildingNameType {
  wood: Int
  clayPit: Int
  ironMine: Int
  warehouse: Int
  hospital: Int
  tavern: Int
  market: Int
  secondary: Int
  rallyPoint: Int
  statue: Int
  headquarter: Int
  barracks: Int
  farm: Int
  wall: Int
}
