type BuildingUpgradeConfigType {
  id: ID,
  villageName: String
  buildingOrder: [BuildingOrderType]
  buildingPriority: BuildingPriorityType
  executedTimes: Int
  failedTimes: Int
  executedAt: DateTime
  nextExecutionAt: DateTime
}
