type FarmingConfigType {
  id: ID,
  minRetrialIntervalInMinutes: Float
  playerVillagesToAllow: [PlayerVillageAttackType]
  playerVillageNamesToIgnore: [String]
  barbarianVillagesArea: BarbarianVillagesAreaType
  barbarianVillageNamesToIgnore: [String]
  presetsNameStartsWith: String
  barbarianVillagesToIgnore: BarbarianVillagesToIgnoreType
  maxNonBarbarianVillagesPoints: Int
  maxOutgoingAttacksAllowed: Int
  maxAllowedAvailableResourcesInPercentage: Percentage
  executedTimes: Int
  executedAt: DateTime
}

type PlayerVillageAttackType {
  name: String
  preferredPresetsOrder: [String]
  maxOutgoingAttacksAllowed: Int
}

type BarbarianVillagesAreaType {
  width: Int
  height: Int
}

type BarbarianVillagesToIgnoreType {
  toAttack: Boolean
  fromAttack: Boolean
}
