type FarmingConfigType {
  id: ID,
  minimumIntervalInMinutes: Float,
  playerVillagesToAllow: [PlayerVillageAttackType],
  playerVillageNamesToIgnore: [String],
  barbarianVillagesArea: BarbarianVillagesAreaType,
  barbarianVillageNamesToIgnore: [String],
  presetsNameStartsWith: String,
  barbarianVillagesToIgnore: BarbarianVillagesToIgnoreType
  nonBarbarianVillagesPointsLimit: Int
  executedTimes: Int
  executedAt: DateTime
}

type PlayerVillageAttackType {
  name: String,
  preferredPresetsOrder: [String]
}

type BarbarianVillagesAreaType {
  width: Int,
  height: Int
}

type BarbarianVillagesToIgnoreType {
  toAttack: Boolean,
  fromAttack: Boolean
}
