type AllConfigsType {
  farmingConfigs: [FarmingConfigType]
  recruitConfigs: [RecruitConfigType]
  attackSchedulers: [AttackSchedulerType]
  buildingUpgradeConfigs: [BuildingUpgradeConfigType]
  tradingResourcesConfigs: [TradingResourcesConfigType]
}

