type RecruitConfigType {
  id: ID,
  recruitmentInstructions: [RecruitmentInstructionsType]
  playerVillagesToAllow: [PlayerVillageRecruitType],
  playerVillageNamesToIgnore: [String],
  executedTimes: Int
  executedAt: DateTime
}

type RecruitmentInstructionsType {
  amount: Int,
  unitType: UnitType
  isHOO: Boolean
}

type PlayerVillageRecruitType {
  name: String,
  recruitmentInstructions: [RecruitmentInstructionsType]
}
