type ResourceDepositConfigType {
  id: ID,
  minRetrialIntervalInMinutes: Int
  nextResourceDepositJobPriority: ResourceDepositJobPriority
  villageToCollectResourceDepositPriority: VillageToCollectResourceDepositPriority
  executedTimes: Int
  failedTimes: Int
  executedAt: DateTime
}
