type TradingResourcesConfigType {
  id: ID
  accountId: String
  minRetrialIntervalInMinutes: Int
  sourceVillageAvailableResourcesRichThresholdInPercent: Percentage
  sourceVillageAvailableResourcesThresholdInPercent: Percentage
  targetVillageAvailableResourcesPoorThresholdInPercent: Percentage
  targetVillageAvailableResourcesThresholdInPercent: Percentage
  sourceVillageNamesToIgnore: [String]
  targetVillageNamesToIgnore: [String]
  maxTransportsToUseInPercent: Percentage
  tradingOrder: TradingOrder
  executedTimes: Int
  failedTimes: Int
  executedAt: DateTime
}
