input AttackSchedulerInput {
  originVillageName: String!
  targets: [String]!
  unitType: UnitType!
  arrivalDate: DateTime!
  timezone: String
  presetConfig: PresetConfigInput
}

input PresetConfigInput {
  name: String!
  waitBetweenAttacksInMs: Int = 1000
  numberOfAttacks: Int = 1
}
