input BuildingUpgradeConfigInput {
  "Name of the player village that requires a building upgrades"
  villageName: String
  "Building upgrade commands that must be executed"
  buildingCommands: [BuildingCommandType] = [RESOURCES]
  "Priority for the provided building commands"
  buildingPriority: BuildingPriorityType = CHEAP
  "Maximum level for every building that should be reached"
  maxLevelPerBuildingName: MaxLevelPerBuildingNameInput
}

input MaxLevelPerBuildingNameInput {
  wood: Int
  clayPit: Int
  ironMine: Int
  warehouse: Int
  hospital: Int
  tavern: Int
  market: Int
  secondary: Int
  rallyPoint: Int
  statue: Int
  headquarter: Int
  barracks: Int
  farm: Int
  wall: Int
}
