input FarmingConfigInput {
  "Minimum minutes until next farming attack."
  minimumIntervalInMinutes: Float,
  "List of your villages that will be used for this farming configuration."
  playerVillagesToAllow: [PlayerVillageFarmingInput],
  "List of village names NOT to be included in the attack."
  playerVillageNamesToIgnore: [String],
  """
  Area that is considered for the farming attack, with your village in the center of the area.
  """
  barbarianVillagesArea: BarbarianVillagesAreaInput,
  barbarianVillageNamesToIgnore: [String],
  presetsNameStartsWith: String,
  barbarianVillagesToIgnore: BarbarianVillagesToIgnoreInput
  nonBarbarianVillagesPointsLimit: Int
  barbarianVillagesPointsLimit: Int
  shufflePlayerVillages: Boolean
}

input PlayerVillageFarmingInput {
  name: String,
  preferredPresetsOrder: [String]
}

input BarbarianVillagesAreaInput {
  width: Int,
  height: Int
}

input BarbarianVillagesToIgnoreInput {
  toAttack: Boolean,
  fromAttack: Boolean
}
