input FarmingConfigInput {
  minimumIntervalInMinutes: Float,
  playerVillagesToAllow: [PlayerVillageAttackInput],
  playerVillageNamesToIgnore: [String],
  barbarianVillagesArea: BarbarianVillagesAreaInput,
  barbarianVillageNamesToIgnore: [String],
  presetsNameStartsWith: String,
  barbarianVillagesToIgnore: BarbarianVillagesToIgnoreInput
  nonBarbarianVillagesPointsLimit: Int
  barbarianVillagesPointsLimit: Int
  shufflePlayerVillages: Boolean
}

input PlayerVillageAttackInput {
  name: String,
  preferredPresetsOrder: [String]
}

input BarbarianVillagesAreaInput {
  width: Int,
  height: Int
}

input BarbarianVillagesToIgnoreInput {
  toAttack: Boolean,
  fromAttack: Boolean
}
