input SpyRecruitConfigInput {
  maxRecruitSpies: Int! = 2
  villagesToIgnore: [String]
}

input MassDonationConfigInput {
  "Percentage that should be donated"
  percentage: Int! = 15
  "List of player village names to allow donation"
  playerVillageNamesToAllow: [String]
  "List of player village names to ignore donation"
  playerVillageNamesToIgnore: [String]
}
